added classes
alexander-deb/EpicSnakes pull request #1
Opened 2021-03-28 16:54 UTC by alexander-deb

2021-04-07 14:57 UTC, AlekIks requested changes
Must have:
- Я не могу отправлять в master и оценивать код, который у меня не работает. В main.cpp вы создаете игру. А она вообще создалась? Как мне проверять, что паттерн работает и порождает объекты? [upd: а какой паттерн мне вообще проверять на работоспособность?]
- Пропишите хотя бы минимальный Readme с инструкцией к запуску. Hint: не обязательно запускать всю игру, тем более, что она не готова; но можно запускать тесты под конкретные классы.
- Разнесите определения классов и реализацию методов.

Рекомендация:
- Добавьте свою диаграмму классов куда-нибудь в этот репозиторий. Если не хотите в Readme, сверху еще есть раздел Wiki.

2021-04-07 14:57 UTC, AlekIks commented on classes/Apple.hpp
> +        _bonus = '0';
Это строка? Точно?

2021-04-07 14:57 UTC, AlekIks commented on .directory
> +[Dolphin]
? Это служебный файл Dolphin?

2021-04-07 14:57 UTC, AlekIks commented on classes/Apple.hpp
> +    void give(Snake snake) {
Яблоко получает змею, а потом кому-то что-то отдает, так и должно быть? Если речь пойдет о бонусах, то ок, но по названию метода непонятно.

2021-04-07 14:57 UTC, AlekIks commented on classes/Apple.hpp
> +#include "Product.hpp"
Каждому hpp по pragma once и cpp!

2021-04-07 14:57 UTC, AlekIks commented on classes/Director.hpp
> +class Director {
Кто такой директор? С кем он взаимодействует и за что отвечает? Это GameMaster? ObjectCreator? God? GameController?

2021-04-07 14:57 UTC, AlekIks commented on classes/Game.hpp
> +    AppleBuilder _applebuilder;
Вы ведь хотели сделать один FruitBuilder... Вам точно нужны все эти строители? У всех этих объектов потенциально сложные конструкторы? Аргументируйте использование паттернов, пожалуйста.

2021-04-07 14:57 UTC, AlekIks commented on classes/Game.hpp
> +    Game(){
Хотели же делать синглтон. А какой тогда мне паттерн проверять?

2021-04-14 05:00 UTC, Dustin-RS commented on classes/Apple.hpp
> +        _bonus = '0';
Да, тут идея в том, что будет написано какой бонус он дает, а потом в классе змея, он будет смотреть на эту строку, и в зависимости от того что там написано, давать определенные бонусы. К примеру, змейка съела яблоко, а яблоко дает бонус к скорости, и в бонусе записана строке "speed", из-за чего, скорость змейки увеличивается.

2021-04-14 05:01 UTC, Dustin-RS commented on classes/Apple.hpp
> +    void give(Snake snake) {
Да, тут речь идет о бонусах. Хорошо, название метода будет изменено.

2021-04-14 05:06 UTC, Dustin-RS commented on classes/Director.hpp
> +class Director {
Директор - это класс для взаимодействия с билдерами. На вход он принимает билдер, а в последствии работает с ним. К примеру, нам нужен билдер яблока, мы создаем экземпляр класса директор, затем устанавливаем ему билдер через метод сет_билдер значение, в нашем случае это applebuilder(Экземпляр класса AppleBuilder), и затем вызываем геттер get_apple(). Он возвращает указатель на созданные яблоки. 
ObjectCreator
Переписал инклуды директора.

2021-04-14 05:11 UTC, Dustin-RS commented on classes/Game.hpp
> +    AppleBuilder _applebuilder;
Изначально да, идея была в создании одного билдера. Однако, с этой идей возникла следующая проблема: у нас класс Fruit является абстрактным.  Также при работе с классом Fruit, в силу того что он абстрактный, возникали следующие трудности: создание абстрактного билдера, что очевидно бред. 
Да, к сожалению, из-за этого приходиться дочерние классы реализовывать повторно, что делает проект довольно хрупким, однако другого выхода мы не увидели. Была идея сделать класс Fruit неабстрактным, но это немного убивает логику проекта.

2021-04-14 05:40 UTC, Dustin-RS commented on classes/Game.hpp
> +    Game(){
Над синглотоном еще думаем. А так релизован паттерн биледр.
P.s можно же реализовать несколько паттернов?

2021-04-19 01:54 UTC, AlekIks commented on classes/Apple.hpp
> +        _bonus = '0';
А бонусы не будут стакаться друг с другом? Например, несколько увеличений скорости? Если да, возможно стоит пересмотреть способ хранения бонусов.
Если нет, то можете еще рассмотреть хранение всех видов бонусов в enum'е. Что можно почитать: https://docs.python.org/3/library/enum.html

2021-04-20 19:45 UTC, AlekIks commented
Здравствуйте!
Пожалуйста, реализуйте проверку того, что ваши порождающие паттерны работают. Например, передайте Директору какие-нибудь параметры и посмотрите, что вернулось. После этого первый чекпоинт будет зачтен.

Замечу, что вы передали обязанности создания объектов Директору, однако при этом напрямую используете билдеры в Game. Не надо так.

2021-04-20 19:51 UTC, closed without merging